# docker-compose.yml

version: '3.9'

services:
  fastapi:
    build: .
    container_name: grantly_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery:
    build: .
    container_name: grantly_celery
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: grantly_redis
    ports:
      - "6379:6379"
